import User from "@/models/User";
import Course from "@/models/Course";
import Expense from "@/models/Expense";
import Institution from "@/models/Institution";
import Lead from "@/models/Lead";
import Program from "@/models/Program";
import Trainee from "@/models/Trainee";
import Trainer from "@/models/Trainer";
import Whitelist from "@/models/Whitelist";